home/urls.py
from django.urls import path
from home import views
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from home.models import Post, Comment, LikeDislike


app_name = 'home'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('comments/<int:pk>/', views.comments, name='comments'),
    path('write_comments/<int:pk>', views.write_comments, name='write_comments'),
    path('delete_comment/<int:pk>', views.delete_comment, name='delete_comment'),
    path('delete_post/<int:pk>', views.delete_post, name='delete_post'),
    path('post_by_me/', views.post_by_me, name='post_by_me'),
    url(r'^post/(?P<pk>\d+)/like/$',
        login_required(views.VotesView.as_view(model=Post, vote_type=LikeDislike.LIKE)),
        name='post_like'),
    url(r'^post/(?P<pk>\d+)/dislike/$',
        login_required(views.VotesView.as_view(model=Post, vote_type=LikeDislike.DISLIKE)),
        name='post_dislike'),
    url(r'^comment/(?P<pk>\d+)/like/$',
        login_required(views.VotesView.as_view(model=Comment, vote_type=LikeDislike.LIKE)),
        name='comment_like'),
    url(r'^comment/(?P<pk>\d+)/dislike/$',
        login_required(views.VotesView.as_view(model=Comment, vote_type=LikeDislike.DISLIKE)),
        name='comment_dislike'),
]

reg/urls.py
from __future__ import unicode_literals
from django.contrib import admin
from django.urls import path, include
from reg import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import password_reset_complete

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('account/', include("accounts.urls")),
    path('home/', include("home.urls")),
    path('friendship/', include("friendship.urls")),
    path('reset-password/complete/', password_reset_complete, {'template_name': 'accounts/password_reset_complete.html'}, name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.db.models import Sum
from django.contrib.contenttypes.fields import GenericRelation


class LikeDislikeManager(models.Manager):
    use_for_related_fields = True

    def likes(self):
        # We take the queryset with records greater than 0
        return self.get_queryset().filter(vote__gt=0)

    def dislikes(self):
        # We take the queryset with records less than 0
        return self.get_queryset().filter(vote__lt=0)

    def sum_rating(self):
        # We take the total rating
        return self.get_queryset().aggregate(Sum('vote')).get('vote__sum') or 0

    def post(self):
        return self.get_queryset().filter(content_type__model='post').order_by('-post__pub_date')

    def comments(self):
        return self.get_queryset().filter(content_type__model='comment').order_by('-comment__pub_date')


class LikeDislike(models.Model):
    LIKE = 1
    DISLIKE = -1

    VOTES = (
        (DISLIKE, 'Dislike'),
        (LIKE, 'Like')
    )

    vote = models.SmallIntegerField(choices=VOTES)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    objects = LikeDislikeManager()


class Post(models.Model):
    votes = GenericRelation(LikeDislike, related_query_name='post')
    post = models.CharField(max_length=1000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_image', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.post

    @property
    def cnt(self):
        return self.like_set.all().count()

    @property
    def total_comment(self):
        return self.comment_set.all().count()


class Comment(models.Model):
    votes = GenericRelation(LikeDislike, related_query_name='comment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=1000)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post.post


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} likes \'{self.post.post}\''

home/forms.py
from django import forms
from home.models import Post, Comment


class HomeForm(forms.ModelForm):
    picture = forms.ImageField()
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder':'write your post..'
        }

    ))

    class Meta:
        model = Post
        fields = ('picture', 'post')


class CommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder':'write your comment...'
        }
    ))

    class Meta:
        model = Comment
        fields = ('comment',)

home/views.py
import json

from django.http import HttpResponse
from django.views import View
from django.contrib.contenttypes.models import ContentType
from django.views.generic import TemplateView
from home.forms import HomeForm, CommentForm
from django.shortcuts import redirect, render
from home.models import Post, Comment, Like, LikeDislike
from friendship.models import Friend
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django_ajax.decorators import ajax
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt

@method_decorator(login_required, name='dispatch')
class Home(TemplateView):
    template_name = 'home/home.html'

    def get(self, request):
        form = HomeForm()

        friends_and_user1 = Friend.objects.filter(\
            Q(from_user=request.user)).values_list('to_user', flat=True)

        friends_and_user2 = Friend.objects.filter( \
            Q(to_user=request.user)).values_list('from_user', flat=True)

        posts = Post.objects.filter( \
            Q(user_id__in=friends_and_user1) | \
            Q(user_id__in=friends_and_user2) | \
            Q(user=request.user)).order_by('-created')
        users = User.objects.exclude(id=request.user.id)[1:]
        args = {'form': form, 'posts': posts, 'users': users}
        return render(request, self.template_name, args)

    def post(self, request):
        form = HomeForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            text = form.cleaned_data['post']
            form = HomeForm()
            return redirect('home:home')
        args = {'form': form, 'text': form.cleaned_data['post']}
        return render(request, self.template_name, args)


@login_required()
def comments(request, pk=None):
    template_name = 'home/all_comments.html'
    cmnt = Comment.objects.filter(post_id=pk).order_by('-created')
    post = Post.objects.get(pk=pk)
    count = Comment.objects.filter(post_id=pk).count()
    context = {'cmnt': cmnt, 'post': post, 'count': count}
    return render(request, template_name, context)


# def already_liked_post(user, post):
#     return Like.objects.filter(user=user, post=post).exists()


# @ajax
# def likes(request, pk=None):
#     if request.method == "POST":
#         post = Post.objects.get(id=pk)
#
#         if not already_liked_post(request.user, post):
#             Like.objects.create(user=request.user, post=post)
#         else:
#             Like.objects.filter(user=request.user, post=post).delete()
#
#         likecount = Like.objects.filter(post=post).count()
#         return {'likecount': likecount}
#     else:
#         post = Post.objects.get(id=pk)
#
#         if not already_liked_post(request.user, post):
#             Like.objects.create(user=request.user, post=post)
#         else:
#             Like.objects.filter(user=request.user, post=post).delete()
#
#         likecount = Like.objects.filter(post=post).count()
#         return {'likecount': likecount}
#
#
# class Write_comments(TemplateView):
#     template_name = 'home/write_comments.html'
#
#     def get(self, request):
#         form = CommentForm()
#
#         cmnt = User.comment_set.filter(id=request.user.id)
#         args = {'form': form, 'cmnt': cmnt, 'user': request.user}
#         return render(request, self.template_name, args)
#
#     def post(self, request):
#         form = CommentForm(request.POST)
#         if form.is_valid():
#
#
#             text = form.cleaned_data['comment']
#             form = CommentForm()
#             return redirect('home:write_comment')
#         args = {'form': form}
#         return render(request, self.template_name, args)


@login_required()
def write_comments(request, pk=None):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = Post.objects.get(id=pk)
            comment.save()
            return redirect('home:comments', pk=pk)
        else:
            return redirect('home:write_comments')

    else:
        form = CommentForm()

        cmnt = Comment.objects.filter(post_id=pk, user_id=request.user.id).order_by('-created')
        post = Post.objects.get(pk=pk)
        args = {'form': form, 'cmnt': cmnt, 'post': post}
        return render(request, 'home/write_comments.html', args)


@login_required
def delete_comment(request, pk=None):
    if request.method == 'POST':
        cmnt = Comment.objects.get(pk=pk)
        post_id = cmnt.post_id
        cmnt.delete()
        return redirect('home:comments', pk=post_id)
    else:
        cmnt = Comment.objects.get(pk=pk)
        post_id = cmnt.post_id
        cmnt.delete()
        return redirect('home:write_comments', pk=post_id)


@login_required
def post_by_me(request):
    posts = request.user.post_set.all().order_by('-created')
    context = {'posts': posts}
    return render(request, 'home/post_by_me.html', context)


# @login_required
# def post_liked_by_me(request):
#     likes = Like.objects.filter(user=request.user).order_by('-timestamp')
#
#     context = {'likes': likes}
#     return render(request, 'home/post_liked_by_me.html', context)


@login_required
def delete_post(request, pk=None):
    print("bye")
    pst = Post.objects.filter(pk=pk)
    print(pst)
    pst.delete()
    print("bye3")
    return redirect('home:post_by_me')


class VotesView(View):
    model = None  # Data Model - Articles or Comments
    vote_type = None  # Vote type Like/Dislike

    def post(self, request, pk):
        obj = self.model.objects.get(pk=pk)
        # GenericForeignKey does not support get_or_create
        try:
            likedislike = LikeDislike.objects.get(content_type=ContentType.objects.get_for_model(obj), object_id=obj.id,
                                                  user=request.user)
            if likedislike.vote is not self.vote_type:
                likedislike.vote = self.vote_type
                likedislike.save(update_fields=['vote'])
                result = True
            else:
                likedislike.delete()
                result = False
        except LikeDislike.DoesNotExist:
            obj.votes.create(user=request.user, vote=self.vote_type)
            result = True

        return HttpResponse(
            json.dumps({
                "result": result,
                "like_count": obj.votes.likes().count(),
                "dislike_count": obj.votes.dislikes().count(),
                "sum_rating": obj.votes.sum_rating()
            }),
            content_type="application/json"
        )

home/templates/home/all_comments.html
{% extends 'base.html' %}
<script>

     function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

// Setup AJAX
$(function () {
    $.ajaxSetup({
        headers: { "X-CSRFToken": getCookie("csrftoken") }
    });
});
</script>
{% block body %}
<h2> POST:</h2>
<div class="well well-sm" style="border: 2px solid #B1D1F6;background-color: #ECF8F7;border-radius: 20px" >

 {% if post.picture %}
        <img src= "{{ post.picture.url }}"  alt="no image" style="width: 100%; height: auto;">
    {% endif %}
 {{ post.post }}
 <br><br>
 <i>Posted by {{post.user.get_full_name }} on {{ post.created }}</i>
</div>
 <br>
<p>Total comment on this post : {{count}}</p>
<br>
 {% for c in cmnt %}
<div class="well well-sm" style="border: 2px solid #B1D1F6;background-color: #ECF8F7;border-radius: 20px">
{{ c.comment }}
 <br>
 <a data-id="{{ c.id }}" data-type="comment" data-action="like" title="Like" style="text-decoration: none;" id="likecolor">
        <span class="glyphicon glyphicon-thumbs-up"></span>
        <span data-count="like">{{ c.votes.likes.count }} </span>
    </a>
    <a data-id="{{ c.id }}" data-type="comment" data-action="dislike" title="Dislike" style="text-decoration: none;" id="dislikecolor">
        <span class="glyphicon glyphicon-thumbs-down"></span>
        <span data-count="dislike">{{ c.votes.dislikes.count }} </span>
    </a>
 <br>
<p>comment by {{ c.user.username }} on {{ c.created }}</p>
</div>
 {% endfor %}
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
 <script>

     function getCookie(c_name)
{
    if (document.cookie.length > 0)
    {
        c_start = document.cookie.indexOf(c_name + "=");
        if (c_start != -1)
        {
            c_start = c_start + c_name.length + 1;
            c_end = document.cookie.indexOf(";", c_start);
            if (c_end == -1) c_end = document.cookie.length;
            return unescape(document.cookie.substring(c_start,c_end));
        }
    }
    return "";
 }

// Setup AJAX
$(function () {
    $.ajaxSetup({
        headers: { "X-CSRFToken": getCookie("csrftoken") }
    });
});
 </script>
{% block body %}
    <h1>Home</h1>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.post }}
        <br>
        {{ form.picture }}
        <br>
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
    <br>
<a href="{% url 'home:post_by_me'%}"><button type="button" class="btn btn-success" value="my_post">Show my Post Only</button> </a>

   <br>

    {% for post in posts %}

    <br>
    <div class="well well-sm" style="border: 2px solid #B1D1F6;background-color: #ECF8F7;border-radius: 20px">
    {% if post.picture %}
        <img src= "{{ post.picture.url }}"  alt="no image" style="width: 100%; height: auto;">
    {% endif %}

        {{post.post }}
        <br>
        <br>

    <a data-id="{{ post.id }}" data-type="post" data-action="like" title="Like" style="text-decoration: none;" >

        <span class="glyphicon glyphicon-thumbs-up" id="span1"></span>
        <span data-count="like" style="color:black;font-size:16px;">{{ post.votes.likes.count }} </span>

    </a>
    <a data-id="{{ post.id }}" data-type="post" data-action="dislike" title="Dislike" style="text-decoration: none;">

        <span class="glyphicon glyphicon-thumbs-down" id="span2"></span>
        <span data-count="dislike" style="color:black;font-size:16px;">{{ post.votes.dislikes.count }} </span>

    </a>

    <a href="{% url 'home:comments' pk=post.pk %}"><button type="button" class="btn btn-outline mb1 blue btn-xs">
  View Comments <span class="badge badge-light">{{ post.total_comment }}</span>
</button></a>
    <a href="{% url 'home:write_comments' pk=post.pk %}"><button type="button" class="btn btn-outline mb1 blue btn-xs">
  Write Comment </button></a><br>
        <i>Posted by {{post.user.get_full_name }} on {{ post.created }}</i>
            </div>

    <br>
    <br>
    {% endfor %}
{% endblock %}

home/templates/home/post_by_me.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
<script>

     function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

// Setup AJAX
$(function () {
    $.ajaxSetup({
        headers: { "X-CSRFToken": getCookie("csrftoken") }
    });
});
</script>
{% block body %}
<h1>My Post</h1>
{% for post in posts %}
    <div style="background-color:#D3D3D3,">
    <br>
    <br>
    <div class="well well-sm" style="border: 2px solid #B1D1F6;background-color: #ECF8F7;border-radius: 20px">
    {% if post.picture %}
        <img src= "{{ post.picture.url }}"  alt="no image" style="width: 100%; height: auto;">
    {% endif %}

        {{post.post }}
    <br>
    <br>
     <a data-id="{{ post.id }}" data-type="post" data-action="like" title="Like" style="text-decoration: none;" id="likecolor">
        <button type="button" class="btn btn-outline mb1 blue btn-xs">
         <span class="glyphicon glyphicon-thumbs-up"></span>
        <span data-count="like">{{ post.votes.likes.count }} </span>
        </button>
    </a>
    <a data-id="{{ post.id }}" data-type="post" data-action="dislike" title="Dislike" style="text-decoration: none;" id="dislikecolor">
        <button type="button" class="btn btn-outline mb1 blue btn-xs">
        <span class="glyphicon glyphicon-thumbs-down"></span>
        <span data-count="dislike">{{ post.votes.dislikes.count }} </span>
        </button>
    </a>
    <a href="{% url 'home:comments' pk=post.pk %}"><button type="button" class="btn btn-outline mb1 blue btn-xs">
  View Comments <span class="badge badge-light">{{ post.total_comment }}</span>
</button></a>
    <a href="{% url 'home:write_comments' pk=post.pk %}"><button type="button" class="btn btn-outline mb1 blue btn-xs">
  Write Comment
</button></a>
    <a href="{% url 'home:delete_post' pk=post.pk %}" onclick="return confirm('Are you sure?')"><button type="button"
        class="btn btn-outline mb1 blue btn-xs">Delete</button></a><br>
        <i>Posted by {{post.user.get_full_name }} on {{ post.created }}</i>
    </div>
        </div>
     <br>
    {% endfor %}
{% endblock %}

home/templates/home/post_liked_by_me.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
{% block body %}
<h1>Post Liked by Me</h1>
{% for like in likes %}
    <div style="background-color:#D3D3D3,">
    <br>
    <div class="well well-sm" style="border: 2px solid #B1D1F6;background-color: #ECF8F7;">
    {% if like.post.picture %}
        <img src= "{{ like.post.picture.url }}"  alt="no image" style="width: 100%; height: auto;">
    {% endif %}

        {{like.post.post }}
    <br>
    <br>
    <a id="like" href="{% url 'home:likes' pk=like.post.pk %}" ><button type="button" class="btn btn-outline mb1 blue btn-xs">
  Like <span class="badge badge-light">{{ like.post.cnt }}</span>
</button> </a>
    <a href="{% url 'home:comments' pk=like.post.pk %}"><button type="button" class="btn btn-outline mb1 blue btn-xs">
  View Comments <span class="badge badge-light">{{ like.post.total_comment }}</span>
</button></a>
    <a href="{% url 'home:write_comments' pk=like.post.pk %}"><button type="button" class="btn btn-outline mb1 blue btn-xs">
  Write Comment </button></a>
    <br>
        <i>Posted by {{like.post.user.get_full_name }} on {{ like.post.created }}</i>
    </div>
        </div>
     <br>
    {% endfor %}
{% endblock %}

home/templates/home/write_comments.html
{% extends 'base.html' %}
{% block body %}

<div class="container">

    <div class="col-md-8">
        <br>
        <h3>POST</h3>
        <div class="well well-sm" style="border: 2px solid #B1D1F6;background-color: #ECF8F7;">
            {% if post.picture %}
        <img src= "{{ post.picture.url }}"  alt="no image" style="width: 100%; height: auto;">
    {% endif %}
            {{ post.post }}
        </div>
        <h1>Write your Comment</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.comment }}
        <br>
        <button class="btn btn-success btn-sm" type="submit">Submit</button>
    </form>
        <br>
        <h3>My Previous Comments to this Post:</h3>
    {% for c in cmnt %}

     <div class="well well-sm" style="border: 2px solid #B1D1F6;background-color: #ECF8F7;">
        {{c.comment}}
        <br>
         <a data-id="{{ post.id }}" data-type="post" data-action="like" title="Like" style="text-decoration: none;" id="likecolor">
        <button type="button" class="btn btn-outline mb1 blue btn-xs">
        <span class="glyphicon glyphicon-thumbs-up"></span>
        <span data-count="like">{{ post.votes.likes.count }} </span>
        </button>
    </a>
    <a data-id="{{ post.id }}" data-type="post" data-action="dislike" title="Dislike" style="text-decoration: none;" id="dislikecolor">
        <button type="button" class="btn btn-outline mb1 blue btn-xs">
        <span class="glyphicon glyphicon-thumbs-down"></span>
        <span data-count="dislike">{{ post.votes.dislikes.count }} </span>
        </button>
    </a>
         <a href="{% url 'home:delete_comment' pk=c.pk %}"><button type="button" class="btn btn-xs btn-danger" value="Delete">Delete</button> </a>
            <br>

         <p><i> comment by {{c.user.get_full_name }} on {{ c.created }}</i>

     </div>
     </div>
    {% endfor %}
        </div>


{% endblock %}