accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.auth.views import (
    login, logout,
    password_reset, password_reset_done,
    password_reset_confirm, password_reset_complete
)
from django.shortcuts import reverse

app_name = 'accounts'
urlpatterns = [
path('', views.home, name="home"),
    path('aftersignup/', views.after_register, name="after_register"),
    path('login/', login, {'template_name': 'accounts/login.html'}, name='login'),
    path('logout/', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/<int:pk>', views.view_profile, name='view_profile_with_pk'),
    path('profile_edit', views.update_profile, name='edit_profile'),
    path('change-password/', views.change_password, name='change_password'),
    path('reset-password/', password_reset, {'template_name': 'accounts/reset_password.html',
                                             'email_template_name': 'accounts/reset_password_mail.html',
                                             'from_email': settings.EMAIL_HOST,
                                             'post_reset_redirect':
                                                 'accounts:password_reset_done'}, name='reset_password'),
    path('reset-password/done/', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/', password_reset_confirm, {'template_name': 'accounts/password_reset_confirm.html'}, name='password_reset_confirm'),


]

home/urls.py
from django.urls import path
from home import views
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from home.models import Post, Comment, LikeDislike


app_name = 'home'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('comments/<int:pk>/', views.comments, name='comments'),
    path('write_comments/<int:pk>', views.write_comments, name='write_comments'),
    path('delete_comment/<int:pk>', views.delete_comment, name='delete_comment'),
    path('delete_post/<int:pk>', views.delete_post, name='delete_post'),
    path('post_by_me/', views.post_by_me, name='post_by_me'),
    url(r'^post/(?P<pk>\d+)/like/$',
        login_required(views.VotesView.as_view(model=Post, vote_type=LikeDislike.LIKE)),
        name='post_like'),
    url(r'^post/(?P<pk>\d+)/dislike/$',
        login_required(views.VotesView.as_view(model=Post, vote_type=LikeDislike.DISLIKE)),
        name='post_dislike'),
    url(r'^comment/(?P<pk>\d+)/like/$',
        login_required(views.VotesView.as_view(model=Comment, vote_type=LikeDislike.LIKE)),
        name='comment_like'),
    url(r'^comment/(?P<pk>\d+)/dislike/$',
        login_required(views.VotesView.as_view(model=Comment, vote_type=LikeDislike.DISLIKE)),
        name='comment_dislike'),
]

reg/urls.py
from __future__ import unicode_literals
from django.contrib import admin
from django.urls import path, include
from reg import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import password_reset_complete

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('account/', include("accounts.urls")),
    path('home/', include("home.urls")),
    path('friendship/', include("friendship.urls")),
    path('reset-password/complete/', password_reset_complete, {'template_name': 'accounts/password_reset_complete.html'}, name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from accounts.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        
        if commit:
            user.save()

        return user


class EditUserForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',

        )

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',

        )


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    description = forms.CharField(required=True)
    city = forms.CharField(required=True)
    website = forms.URLField()
    phone = forms.IntegerField()
    image = forms.ImageField()

    class Meta:
        model = UserProfile
        fields = ('description', 'city', 'website', 'phone', 'image')


class PasswordResetRequestForm(forms.Form):
    email_or_username = forms.CharField(label=("Email Or Username"), max_length=254)


class SetPasswordForm(forms.Form):
    """
    A form that lets a user change set their password without entering the old
    password
    """
    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
    }
    new_password1 = forms.CharField(label="New password",
                                    widget=forms.PasswordInput)
    new_password2 = forms.CharField(label="New password confirmation",
                                    widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['new_password1'])
        if commit:
            self.user.save()
        return self.user

home/forms.py
from django import forms
from home.models import Post, Comment


class HomeForm(forms.ModelForm):
    picture = forms.ImageField()
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder':'write your post..'
        }

    ))

    class Meta:
        model = Post
        fields = ('picture', 'post')


class CommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder':'write your comment...'
        }
    ))

    class Meta:
        model = Comment
        fields = ('comment',)

accounts/views.py
from django.shortcuts import render,redirect
from accounts.forms import (
    RegistrationForm,
    EditProfileForm,
    UserForm,
    ProfileForm,
    SetPasswordForm,
    PasswordResetRequestForm
)
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template import loader
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.conf import settings

from django.views.generic import *

from django.contrib import messages
from django.contrib.auth.models import User
from django.db.models.query_utils import Q


def home(request):

    return redirect('home:home')


def after_register(request):

    return render(request, "accounts/signup_success.html", context=None)


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/account/aftersignup')
        else:
            print("hello")

    else:
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)


@login_required()
def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user}
    return render(request, 'accounts/profile.html', args)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/account/profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


@login_required
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST or None, request.FILES or None, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('accounts:view_profile')
        else:
            print("error")
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.userprofile)
    return render(request, 'accounts/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('/account/profile')
        else:
            messages.error(request, 'Please correct the error below.')
            return redirect('/account/change-password')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)


class ResetPasswordRequestView(FormView):
    template_name = "accounts/test_template.html"  # code for template is given below the view's code
    success_url = "/account/login"
    form_class = PasswordResetRequestForm

    @staticmethod
    def validate_email_address(email):
        '''
        This method here validates the if the input is an email address or not. Its return type is boolean, True if the input is a email address or False if its not.
        '''

        try:
            validate_email(email)
            return True
        except ValidationError:
            return False

    def post(self, request, *args, **kwargs):
        '''
        A normal post request which takes input from field "email_or_username" (in ResetPasswordRequestForm).
        '''

        form = self.form_class(request.POST)
        if form.is_valid():
            data = form.cleaned_data["email_or_username"]
        if self.validate_email_address(data) is True:  # uses the method written above
            '''
            If the input is an valid email address, then the following code will lookup for users associated with that email address. If found then an email will be sent to the address, else an error message will be printed on the screen.
            '''
            associated_users = User.objects.filter(Q(email=data) | Q(username=data))
            if associated_users.exists():
                for user in associated_users:
                    c = {
                        'email': user.email,
                        'domain': request.META['HTTP_HOST'],
                        'site_name': 'your site',
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'user': user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                        }
                    subject_template_name = 'accounts/password_reset_subject.txt'
                    # copied from django/contrib/admin/templates/registration/password_reset_subject.txt to templates directory
                    email_template_name = 'accounts/password_reset_email.html'
                    # copied from django/contrib/admin/templates/registration/password_reset_email.html to templates directory
                    subject = loader.render_to_string(subject_template_name, c)
                    # Email subject *must not* contain newlines
                    subject = ''.join(subject.splitlines())
                    email = loader.render_to_string(email_template_name, c)
                    send_mail(subject, email, settings.DEFAULT_FROM_EMAIL, [user.email], fail_silently=False)
                result = self.form_valid(form)
                messages.success(request,
                             'An email has been sent to ' + data + ". Please check its inbox to continue reseting password.")
                return result
            result = self.form_invalid(form)
            messages.error(request, 'No user is associated with this email address')
            return result
        else:
            '''
            If the input is an username, then the following code will lookup for users associated with that user. If found then an email will be sent to the user's address, else an error message will be printed on the screen.
            '''
            associated_users = User.objects.filter(username=data)
            if associated_users.exists():
                for user in associated_users:
                    c = {
                        'email': user.email,
                        'domain': 'example.com',  # or your domain
                        'site_name': 'example',
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'user': user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                        }
                    subject_template_name = 'accounts/password_reset_subject.txt'
                    email_template_name = 'accounts/password_reset_email.html'
                    subject = loader.render_to_string(subject_template_name, c)
                    # Email subject *must not* contain newlines
                    subject = ''.join(subject.splitlines())
                    email = loader.render_to_string(email_template_name, c)
                    send_mail(subject, email, settings.DEFAULT_FROM_EMAIL, [user.email], fail_silently=False)
                result = self.form_valid(form)
                messages.success(request,
                             'Email has been sent to ' + data + "'s email address. Please check its inbox to continue reseting password.")
                return result
            result = self.form_invalid(form)
            messages.error(request, 'This username does not exist in the system.')
            return result
        messages.error(request, 'Invalid Input')
        return self.form_invalid(form)


class PasswordResetConfirmView(FormView):
    template_name = "accounts/test_template.html"
    success_url = '/admin/'
    form_class = SetPasswordForm

    def post(self, request, uidb64=None, token=None, *arg, **kwargs):
        """
        View that checks the hash in a password reset link and presents a
        form for entering a new password.
        """
        UserModel = get_user_model()
        form = self.form_class(request.POST)
        assert uidb64 is not None and token is not None  # checked by URLconf
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = UserModel._default_manager.get(pk=uid)
        except (TypeError, ValueError, OverflowError):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            if form.is_valid():
                new_password = form.cleaned_data['new_password2']
                user.set_password(new_password)
                user.save()
                messages.success(request, 'Password has been reset.')
                return self.form_valid(form)
            else:
                messages.error(request, 'Password reset has not been unsuccessful.')
                return self.form_invalid(form)
        else:

reg/views.py
from django.shortcuts import redirect


def login_redirect(request):
    if request.user.is_authenticated:
        return redirect('/home')
    else:
        return redirect('/account/login')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="col-md-1"></div>
    <div class="col-md-6" style=" border: 2px solid #53C44B;
    border-radius: 12px;">
<h1>Profile Edit</h1>
<br>


<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success" type="submit">Save</button>
</form>
    </div>
    </div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
<h1>Profile Edit</h1>
<br>
    <form method="post" action="" enctype="multipart/form-data">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <button class="btn btn-success" type="submit">Save changes</button>
</form>
{% endblock %}
</div>

accounts/templates/accounts/home.html
{% extends 'base.html' %}


    {% block head %}
    <title>Home</title>
    {% endblock %}

<div class = "container">
{% block body %}

<h1>This is your HomePage {{user}}</h1>


    {% endblock %}

    </div>

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
    <div class="col-md-2"></div>
    <div class="col-md-4" style=" border: 2px solid #53C44B;
    border-radius: 12px;">
<h1>Welcome</h1>
<p>
    You can login here
</p>
<h2>Login</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="col-md-4"></div><button class="btn btn-success" type="submit">Login</button>


</form>

    </div>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
<h1>You Logged Out Successfully</h1>
{% endblock %}
</div>

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
    <div class="col-md-2"></div>
    <div class="col-md-4" style=" border: 2px solid #53C44B;
    border-radius: 12px;">
<h4>Password Changed Successfully <a href="{% url 'accounts:login' %}"><button class="btn btn-success">Login</button></a></h4>


          </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% block body %}
<div class="container" >
    <div class="col-md-2"></div>
    <div class="col-md-4" style=" border: 2px solid #53C44B;
    border-radius: 12px;">

{% if validlink %}

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form action="" method="post">
	{% csrf_token %}
{{ form.new_password1.errors }}
<p class="aligned wide"><label for="id_new_password1">New password:</label>{{ form.new_password1 }}</p>
{{ form.new_password2.errors }}
<p class="aligned wide"><label for="id_new_password2">Confirm password:</label>{{ form.new_password2 }}</p>
<p><input type="submit" class="btn btn-success" value="Change my password" /></p>
</form>

{% else %}

<p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>

{% endif %}

    </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}


    {% block head %}
    <title>Home</title>
    {% endblock %}

{% block body %}
<div class="container">
    <h1>Profile</h1>
    <div class="col-md-4">
    <p>Username : {{ user }}</p>
    <p>First Name : {{ user.first_name }}</p>
    <p>Last Name : {{ user.last_name }}</p>
    <p>Email : {{ user.email }}</p>
    <p>Description : {{ user.userprofile.description }}</p>
    <p>City : {{ user.userprofile.city }}</p>
    <p>Website : {{ user.userprofile.website }}</p>
    <p>Phone : {{ user.userprofile.phone }}</p>
</div>
<div class="col-md-4">
    {% if user.userprofile.image %}
        <img src= "{{ user.userprofile.image.url}}" alt="no image" style="width: 200px; height: 200px;">
    {% endif %}
</div>
</div>
{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="col-md-8" style=" border: 2px solid #53C44B;
    border-radius: 12px;">
<h1>Sign Up</h1>
<br>


<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="col-md-4"></div><button class="btn btn-success" type="submit">Sign Up</button>
</form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="col-md-2"></div>
    <div class="col-md-4" style=" border: 2px solid #53C44B;
    border-radius: 12px;">
    <h2>RESET YOUR PASSWORD</h2>

    <h3>Enter the Information:</h3>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="col-md-2"></div>
        <button class="btn btn-danger" type="submit">Reset Password</button>


    </form>
</div>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="col-md-8">
<h1>A Password reset link has been sended to your mail if exist</h1>
    </div>
{% endblock %}
</div>

accounts/templates/accounts/reset_password_mail.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
    {% block reset_link %}
        {{ site_name }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

    {% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/accounts/signup_success.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
<h1>Welcome</h1>
<p>
    You have Registered Successfully
</p>
<h2>Now you can Login</h2>
   <form action="/account/login" method="get">
       <input type="submit" value="Login" name="Login">
   </form>
{% endblock %}
</div>