friendship/urls.py
from django.urls import path
try:
    from django.conf.urls import url
except ImportError:
    from django.conf.urls.defaults import url
from friendship.views import view_friends, friendship_add_friend, friendship_accept, \
    friendship_reject, friendship_cancel, friendship_request_list, \
    friendship_request_list_rejected, friendship_requests_detail, all_users


app_name = 'friendship'
urlpatterns = [
    url(
        regex=r'^users/$',
        view=all_users,
        name='friendship_view_users',
    ),
    url(
        regex=r'^friends/(?P<username>[\w-]+)/$',
        view=view_friends,
        name='friendship_view_friends',
    ),
    url(
        regex=r'^friend/add/(?P<to_username>[\w-]+)/$',
        view=friendship_add_friend,
        name='friendship_add_friend',
    ),
    url(
        regex=r'^friend/accept/(?P<friend>[\w-]+)/$',
        view=friendship_accept,
        name='friendship_accept',
    ),
    url(
        regex=r'^friend/reject/(?P<friend>[\w-]+)/$',
        view=friendship_reject,
        name='friendship_reject',
    ),
    url(
        regex=r'^friend/cancel/(?P<friend>[\w-]+)/$',
        view=friendship_cancel,
        name='friendship_cancel',
    ),
    url(
        regex=r'^friend/requests/$',
        view=friendship_request_list,
        name='friendship_request_list',
    ),
    url(
        regex=r'^friend/requests/rejected/$',
        view=friendship_request_list_rejected,
        name='friendship_requests_rejected',
    ),
    url(
        regex=r'^friend/request/(?P<friendship_request_id>\d+)/$',
        view=friendship_requests_detail,
        name='friendship_requests_detail',
    ),

]

reg/urls.py
from __future__ import unicode_literals
from django.contrib import admin
from django.urls import path, include
from reg import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import password_reset_complete

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('account/', include("accounts.urls")),
    path('home/', include("home.urls")),
    path('friendship/', include("friendship.urls")),
    path('reset-password/complete/', password_reset_complete, {'template_name': 'accounts/password_reset_complete.html'}, name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friendship/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.db.models import Q
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from friendship.exceptions import AlreadyExistsError, AlreadyFriendsError
from friendship.signals import (
    friendship_request_created, friendship_request_rejected,
    friendship_request_canceled,
    friendship_request_viewed, friendship_request_accepted,
    friendship_removed)

@python_2_unicode_compatible
class FriendshipRequest(models.Model):
    """ Model to represent friendship requests """
    from_user = models.ForeignKey(User, related_name='friendship_requests_sent', on_delete=models.CASCADE, unique=False)
    to_user = models.ForeignKey(User, related_name='friendship_requests_received', on_delete=models.CASCADE, unique=False)

    message = models.TextField(_('Message'), blank=True)

    created = models.DateTimeField(default=timezone.now)
    rejected = models.DateTimeField(blank=True, null=True)
    viewed = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name = _('Friendship Request')
        verbose_name_plural = _('Friendship Requests')
        unique_together = ('from_user', 'to_user')

    def __str__(self):
        return "%s" % self.from_user.username

    def accept(self):
        """ Accept this friendship request """
        relation1 = Friend.objects.create(
            from_user=self.from_user,
            to_user=self.to_user
        )

        relation2 = Friend.objects.create(
            from_user=self.to_user,
            to_user=self.from_user
        )

        friendship_request_accepted.send(
            sender=self,
            from_user=self.from_user,
            to_user=self.to_user
        )

        self.delete()

        # Delete any reverse requests
        FriendshipRequest.objects.filter(
            from_user=self.to_user,
            to_user=self.from_user
        ).delete()

        return True

    def reject(self):
        """ reject this friendship request """
        self.rejected = timezone.now()
        self.save()
        friendship_request_rejected.send(sender=self)


    def cancel(self):
        """ cancel this friendship request """
        self.delete()
        friendship_request_canceled.send(sender=self)
        return True

    def mark_viewed(self):
        self.viewed = timezone.now()
        friendship_request_viewed.send(sender=self)
        self.save()
        return True


@python_2_unicode_compatible
class Friend(models.Model):
    """ Model to represent Friendships """
    to_user = models.ForeignKey(User, related_name='friends', on_delete=models.CASCADE)
    from_user = models.ForeignKey(User, related_name='_unused_friend_relation', on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = _('Friend')
        verbose_name_plural = _('Friends')
        unique_together = ('from_user', 'to_user')

    def __str__(self):
        return "User #%s is friends with #%s" % (self.to_user.username, self.from_user.username)

    def mutual(self, request):
        count = 0
        touserfriend1 = Friend.objects.filter(from_user=request.user).values_list('to_user', flat=True)
        touserfriend2 = Friend.objects.filter(to_user=request.user).values_list('from_user', flat=True)
        total_friend1 = list(touserfriend1).append(list(touserfriend2))

        fromuserfriend1 = Friend.objects.filter(from_user=self).values_list('to_user', flat=True)
        fromuserfriend2 = Friend.objects.filter(to_user=self).values_list('from_user', flat=True)
        total_friend2 = list(fromuserfriend1).append(list(fromuserfriend2))

        for x in total_friend1:
            for y in total_friend2:
                if x == y:
                    count = count+1
        return count

    def save(self, *args, **kwargs):
        # Ensure users can't be friends with themselves
        if self.to_user == self.from_user:
            raise ValidationError("Users cannot be friends with themselves.")
        super(Friend, self).save(*args, **kwargs)

friendship/views.py
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth.models import User

from friendship.templatetags.friendshiptags import register

try:
    from django.contrib.auth import get_user_model

    user_model = get_user_model()
except ImportError:
    from django.contrib.auth.models import User

    user_model = User

from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from friendship.exceptions import AlreadyExistsError
from friendship.models import Friend, FriendshipRequest

get_friendship_context_object_name = lambda: getattr(settings, 'FRIENDSHIP_CONTEXT_OBJECT_NAME', 'user')
get_friendship_context_object_list_name = lambda: getattr(settings, 'FRIENDSHIP_CONTEXT_OBJECT_LIST_NAME', 'users')


@login_required
def view_friends(request, username, template_name='friendship/friend/user_list.html'):
    """ View the friends of a user """
    myfriends = Friend.objects.filter( \
        Q(from_user=request.user) | \
        Q(to_user=request.user))
    user = request.user
    return render(request, template_name, {
        'myfriends': myfriends, 'user': user
    })


@login_required
def friendship_add_friend(request, to_username, template_name='friendship/friend/add.html'):
    """ Create a FriendshipRequest """
    ctx = {'to_username': to_username}

    if request.method == 'GET':
        to_user = User.objects.get(username=to_username)
        from_user = request.user
        rqst=FriendshipRequest.objects.create(from_user=from_user, to_user=to_user)
        rqst.save()
        return redirect('friendship:friendship_view_users')

    return render(request, template_name, ctx)


@login_required
def friendship_accept(request, friend):
    """ Accept a friendship request """
    if request.method == 'GET':
        user = User.objects.get(username=friend)
        f_request = Friend.objects.create(from_user=user, to_user=request.user)
        f_request.save()
        FriendshipRequest.objects.get(from_user=user, to_user=request.user, rejected__isnull=True).mark_viewed()
        return redirect('friendship:friendship_view_friends', username=request.user.username)

    return redirect('friendship:friendship_request_list')


@login_required
def friendship_reject(request, friend):
    """ Reject a friendship request """
    if request.method == 'GET':
        user = User.objects.get(username=friend)
        f_request = FriendshipRequest.objects.get(to_user=request.user, from_user=user)
        f_request.reject()
        return redirect('friendship:friendship_request_list')

    return redirect('friendship:friendship_request_list')


@login_required
def friendship_cancel(request, friend):
    """ Cancel a previously created friendship_request_id """

    if request.method == 'GET':
        getid = User.objects.get(username = friend)
        Friend.objects.filter(\
            Q(from_user=request.user, to_user_id=getid.id) |\
            Q(from_user_id=getid.id, to_user=request.user) \
        ).delete()
        FriendshipRequest.objects.filter( \
            Q(from_user=request.user, to_user_id=getid.id) | \
            Q(from_user_id=getid.id, to_user=request.user) \
            ).delete()

        return redirect('friendship:friendship_view_friends', username=request.user)

    return redirect('friendship:friendship_view_friends', username=request.user)


@login_required
def friendship_request_list(request, template_name='friendship/friend/requests_list.html'):
    """ View unread and read friendship requests """
    requestme = FriendshipRequest.objects.filter( \
        Q(to_user=request.user, viewed__isnull=True, rejected__isnull=True)).values_list('from_user', flat=True)
    u = request.user
    users = User.objects.filter(id__in=requestme)
    return render(request, template_name, {'users': users, 'u': u})


@login_required
def friendship_request_list_rejected(request, template_name='friendship/friend/requests_list.html'):
    """ View rejected friendship requests """
    # friendship_requests = Friend.objects.rejected_requests(request.user)
    friendship_requests = FriendshipRequest.objects.filter(rejected__isnull=False)

    return render(request, template_name, {'requests': friendship_requests})


@login_required
def friendship_requests_detail(request, friendship_request_id, template_name='friendship/friend/request.html'):
    """ View a particular friendship request """
    f_request = get_object_or_404(FriendshipRequest, id=friendship_request_id)

    return render(request, template_name, {'friendship_request': f_request})


@login_required
def all_users(request):
    already = Friend.objects.filter( \
        Q(from_user=request.user) | \
        Q(to_user=request.user)).values_list('to_user', flat=True)

    requestme = FriendshipRequest.objects.filter( \
        Q(to_user=request.user, rejected__isnull=True)).values_list('from_user', flat=True)

    users = User.objects.exclude( \
        Q(id__in=already) | \
        Q(id=request.user.id) | \
        Q(username="admin") | \
        Q(id__in=requestme)).order_by("username")

    requestbyme = FriendshipRequest.objects.filter( \
        Q(from_user=request.user, viewed__isnull=True)).values_list('to_user', flat=True)

    requestbymeuser = User.objects.filter(id__in=requestbyme)

    return render(request, template_name='friendship/friend/add.html', context={'users': users, 'requestbymeuser': requestbymeuser })


'''@register.filter
def mutual(request,  fromuser):
    count = 0
    touserfriend1 = Friend.objects.filter(from_user=request.user).values_list('to_user', flat=True)
    touserfriend2 = Friend.objects.filter(to_user=request.user).values_list('from_user', flat=True)
    total_friend1 = list(touserfriend1).append(list(touserfriend2))

    fromuserfriend1 = Friend.objects.filter(from_user=fromuser).values_list('to_user', flat=True)
    fromuserfriend2 = Friend.objects.filter(to_user=fromuser).values_list('from_user', flat=True)
    total_friend2 = list(fromuserfriend1).append(list(fromuserfriend2))

    for x in total_friend1:
        for y in total_friend2:
            if x == y:
                count = count+1
    return count'''

friendship/templates/friendship/friend/add.html
{% extends 'base.html' %}
{% block body %}
<div class="col-md-12">
{% for usr in users %}
 <div class="well well-sm " style="border: 2px solid #B1D1F6;background-color: #ECF8F7;border-radius: 20px">
{% if usr in requestbymeuser %}
  {% if usr.userprofile.image %}
        <img src= "{{ usr.userprofile.image.url }}"  alt="no image" style="width: 150px; height: 150px;">
    {% else %}
        <img src= "profile_image/noprofile.png"  alt="no image" style="width: 150px; height: 150px;">
    {% endif %}
  <div class="col-md-9" style="font-size: 22px;font-family: 'Times New Roman', Times, serif;">
   <b>{{ usr.username }} ({{usr.first_name}} {{usr.last_name }})</b>
   <br>
   {% if usr.userprofile.city != "" %}
   <i>{{usr.userprofile.city}}</i>
       <br>
   {% endif %}
   <i>Request Sent</i>
  </div>
{% else %}
  {% if usr.userprofile.image %}
        <img src= "{{ usr.userprofile.image.url }}"  alt="no image" style="width: 150px; height: 150px;">
    {% else %}
        <img src= "profile_image/noprofile.png"  alt="no image" style="width: 150px; height: 150px;">
    {% endif %}
  <div class="col-md-9" style="font-size: 22px;font-family: 'Times New Roman', Times, serif;">
   <b>{{ usr.username }} ({{usr.first_name}} {{usr.last_name }})</b>
   <br>
   {% if usr.userprofile.city != "" %}
   <i>{{usr.userprofile.city}}</i>
       <br>
   {% endif %}
   <a href="{% url 'friendship:friendship_add_friend' to_username=usr.username %}">Add as Friend</a>
  </div>
   {% endif %}
 </div>
<br>
{% endfor %}
</div>
{% endblock %}

friendship/templates/friendship/friend/request.html
{% extends 'base.html' %}
{% block body %}
<div>{{ friendship_request.from_user }} wants to be friends with {{ friendship_request.to_user }}</div>

<form method="post" action="{% url 'friendship:friendship_accept' friendship_request.pk %}">
{% csrf_token %}
<input type="submit" value="accept" />
</form>

<form method="post" action="{% url 'friendship:friendship_reject' friendship_request.pk %}">
{% csrf_token %}
<input type="submit" value="reject" />
</form>
{% endblock %}

friendship/templates/friendship/friend/requests_list.html
{% extends 'base.html' %}
{% block body %}
<div class="col-md-12">
{% for request in users %}
    <div class="well well-sm " style="border: 2px solid #B1D1F6;background-color: #ECF8F7;border-radius: 20px">

  {% if request.userprofile.image %}
        <img src= "{{ request.userprofile.image.url }}"  alt="no image" style="width: 150px; height: 150px;">
    {% else %}
        <img src= "profile_image/noprofile.png"  alt="no image" style="width: 150px; height: 150px;">
    {% endif %}
        <div class="col-md-9" style="font-size: 22px;font-family: 'Times New Roman', Times, serif;">
    {{ request.username }} wants to be your Friend<br>

        <a href="{% url 'friendship:friendship_accept' request %}">Accept</a><br>
        <a href="{% url 'friendship:friendship_reject' request %}">Reject</a>
    <br>
        </div>

</div>

{% endfor %}
    </div>
{% endblock %}

friendship/templates/friendship/friend/user_list.html
{% extends 'base.html' %}
{% block body %}
<h1>My Friends</h1>

<div class="col-md-12">
{% for f in myfriends %}
<div class="well well-sm " style="border: 2px solid #d1dfff ;background-color: #ECF8F7;border-radius: 20px">

    {% if user != f.from_user %}
    {% if f.from_user.userprofile.image %}
        <img src= "{{ f.from_user.userprofile.image.url }}"  alt="no image" style="width: 150px; height: 150px;">
    {% else %}
        <img src= "profile_image/noprofile.png"  alt="no image" style="width: 150px; height: 150px;">
    {% endif %}
<div class="col-md-9" style="font-size: 22px;font-family: 'Times New Roman', Times, serif;">
    <b>{{ f.from_user }} ({{f.from_user.first_name}} {{f.from_user.last_name}})</b>
    <br>
    {% if f.from_user.userprofile.city != "" %}
   <i>{{f.from_user.userprofile.city}}</i>
       <br>
   {% endif %}
    <a href="{% url 'friendship:friendship_cancel' friend=f.from_user %}"> Unfriend</a>
</div>
{% else %}
    {% if f.to_user.userprofile.image %}
        <img src= "{{ f.to_user.userprofile.image.url }}"  alt="no image" style="width: 150px; height: 150px;">
    {% else %}
        <img src= "profile_image/noprofile.png"  alt="no image" style="width: 150px; height: 150px;">
    {% endif %}
<div class="col-md-9" style="font-size: 22px;font-family: 'Times New Roman', Times, serif;">
    <b>{{ f.to_user }}({{f.from_user.first_name}} {{f.from_user.last_name}})</b>
    <br>
    {% if f.to_user.userprofile.city != "" %}
   <i>{{f.to_user.userprofile.city}}</i>
       <br>
   {% endif %}
    <a href="{% url 'friendship:friendship_cancel' friend=f.to_user %}"> Unfriend</a>
</div>
{% endif %}
    <br>
</div>
{% endfor %}
</div>
{% endblock %}